# Generated by Django 5.2.8 on 2025-12-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_task_id_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('completed', 'completed'), ('incompleted', 'Incompleted')], max_length=20),
        ),
    ]
