# Generated by Django 5.2.8 on 2025-12-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='task_name',
            field=models.CharField(default='Unknown Task', max_length=100),
            preserve_default=False,
        ),
    ]
